// src/Showsdata.js

export const upcomingShows = [
  {
    slug: "swim-house-may-10-2025",
    date: "May 10, 2025",              // Display text (for quick editing)
    isoDate: "2025-05-10",            // Machine-readable format for sorting
    location: "Swim House",
    city: "Newark, DE",
    address: "49 Prospect Ave",
    time: "3–5 PM",
    notes: "$5 tickets at door",
    ticketLink: "",                   // optional: external link to Eventbrite, etc.
    soldOut: false,
    free: false,
    private: false,
  },
  {
    slug: "union-firehouse-may-10-2025",
    date: "May 10, 2025",
    isoDate: "2025-05-10",
    location: "Union Firehouse",
    city: "Mount Holly, NJ",
    address: "18 Washington St",
    time: "9 PM set time",
    notes: "$15 tickets at door",
    ticketLink: "",
    soldOut: false,
    free: false,
    private: false,
  },
  {
    slug: "deer-park-botb-may-14-2025",
    date: "May 14, 2025",
    isoDate: "2025-05-14",
    location: "Deer Park Tavern — Battle of the Bands",
    city: "Newark, DE",
    time: "11:20 PM – 1 AM",
    notes: "21+ • Free Entry",
    ticketLink: "",
    soldOut: false,
    free: true,
    private: false,
  },
  {
    slug: "private-event-june-7-2025",
    date: "June 7, 2025",
    isoDate: "2025-06-07",
    location: "Private Event",
    city: "Rehoboth, DE",
    time: "Evening",
    notes: "Private booking",
    soldOut: false,
    free: false,
    private: true,
  },
  {
    slug: "conch-island-june-21-2025",
    date: "June 21, 2025",
    isoDate: "2025-06-21",
    location: "Conch Island",
    city: "Rehoboth Beach, DE",
    time: "9 PM – 12 AM",
    notes: "Free Entry",
    ticketLink: "",
    soldOut: false,
    free: true,
    private: false,
  },
];
