// Combined show/video data in a single source
export const showData = {
  "deer-park-11-29": {
    title: "Deer Park Tavern",
    date: "November 29, 2024",
    pagetitle: "Live At DP 11/29",
    location: "Newark, DE",
    poster: "VGPS3.png",
    heroImages: ["/band2.webp"],
    flyerImage: "VGPS3.png",
    photos: Array.from({ length: 878 }, (_, i) =>
      `/DP1129PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "n7u4uDErGx4", "6ibyAyEUBaI", "XRWI3JZr-oY", "4QrozbzBDZw", "Pk15vTlhkPs",
      "Mdfz0747jPQ", "47At1VIU0aQ", "HNluM8BVYMY", "Ap0LqNnPl2M", "zFt7T11sSb0",
      "3jb0-me2Ukc", "XqYa3la-Mv4", "erNMYMCVqwo", "jt5VT5a-Cqw", "H0Xzyqsf83I",
      "f8tvhMr0QcA", "QZIxEy1jUHY", "ry6CEWvaOR0", "vXufkCqhFbM", "tzu_C7VeHHA",
      "jeeloZJ6bCs", "1ZKG-lNnwF0", "DWYGrfQdEyY", "evwPV-l6SaQ", "OFNiFW6X5bs",
      "cAoCIGsDLOY", "lU-Ttx8YxcU", "KTRabY1d8Rc", "cmPlzl-RmFw", "TeH0aucLAJc",
      "31vzVVi7YRY", "rR2_uP29220", "_6cj5js-5xA", "TsNN5lmJF20", "kDnWD7Y2fwE",
      "_7epDe7eZqg"
    ],
    setlist: [
      { title: "Rock And Roll", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenage Dirtbag" },
      { title: "All The Small Things" },
      { title: "Enter Sandman", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Circling Vultures" },
      { title: "Creep", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenagers" },
      { title: "You Shook Me All Night Long" },
      { title: "Gives You Hell" },
      { title: "(Like It's) Cocaine", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Zombie" },
      { title: "Creeping Death (ft. Tom)" },
      { title: "Cigarette Daydreams" },
      { title: "Air Raid" },
      { title: "Times Like These" },
      { title: "Sunday Morning" },
      { title: "American Idiot" },
      { title: "Nothing Left" },
      { title: "War Pigs" },
      { title: "Cult Of Personality" },
      { title: "Flagpole Sitta" },
      { title: "Beautiful Disaster" },
      { title: "Kilby Girl" },
      { title: "Sweet Home Alabama" },
      { title: "Everybody Talks" },
      { title: "FRM" },
      { title: "Sex On Fire" },
      { title: "Chop Suey" },
      { title: "My Own Inferno" },
      { title: "The Middle" },
      { title: "Digital Lemons" },
      { title: "Killing In The Name" },
      { title: "One Last Breath" },
      { title: "Higher" },
      { title: "Everlong" },
      { title: "Two Weeks Past" },
      { title: "Walk" },
      { title: "Basket Case" },
      { title: "Encore: Bulls On Parade" }
    ]
  },
  "conch-4-26": {
    title: "Conch Island",
    pagetitle: "Live At Conch 4/26",
    date: "April 26, 2025",
    location: "Rehobeth Beach, DE",
    poster: "/showposters/conchisland(POSTversion).webp",
    heroImages: ["/CONCH426PHOTOS/Image93.webp"],
    flyerImage: "showposters/conchisland(POSTversion).webp",
    photos: Array.from({ length: 223 }, (_, i) =>
      `/CONCH426PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "-sRNLKs9_Dw", "zTmUQPjQDio", "9ewZ0CGXG7A", "PUbTzX4pjHY", "88PV_yep3zU",
      "ryx56JTdsMQ", "eWvftcFWZHc", "eK_dCN1XG60", "5vhy-JFAY48",
      "1fnftYyWPWM", "zTtM8AmKgLg", "mf4Ba0QzFSE", "f0ZEu2_xm7o", "zSv_oMAxfHY",
      "DIrAlowrF1c", "kiir280QEVM", "x_n4Gw7kJFQ", "jAlt6cLNZOs", "OhDD5D_rdFM",
      "M-v3wqvhD24", "FQAOsCGZMU8", "H7f2Us9ZVoE", "Y-T_WJATm8g", "U18kQy_RYtY",
      "Mgo6scG9sM", "XCBFO0gkImA", "T0mCbfNM57A", "iNLU98J5vQ8", "qDmhda8i2s4",
      "WHTz2zYj2_Y", "yHbX_NTJ9zU", "Y24d9__dPDY", "q_VuFlxAc7U", "Ylhc7a7FrCU",
      "5oQIE7I3e9s", "DFBk1fOmMRw", "6U3RmjoQQOM", "T0mCbfNM57A", "z7jWK0YHhTc"
    ],
    setlist: [{ title: "One Last Breath" },
      { title: "Rock And Roll" },
      { title: "Teenage Dirtbag" },
      { title: "Cocaine" },
      { title: "Interstate Love Song" },
      { title: "Semi-Charmed Life" },
      { title: "Your Love" },
      { title: "Circling Vultures" },
      { title: "Santeria" },
      { title: "Enter Sandman" },
      { title: "All The Small Things" },
      { title: "Plush" },
      { title: "FRM" },
      { title: "Everybody Talks" },
      { title: "Last Nite" },
      { title: "Flagpole Sitta" },
      { title: "Simple Man" },
      { title: "Are You Gonna Be My Girl" },
      { title: "Good Times Bad Times" },
      { title: "Nothing Left" },
      { title: "American Idiot" },
      { title: "Creep" },
      { title: "The Anthem" },
      { title: "My Own Worst Enemy" },
      { title: "Sex On fire" },
      { title: "Zombie" },
      { title: "My Own Inferno" },
      { title: "Everlong" },
      { title: "Flies Of Desire" },
      { title: "The Middle" },
      { title: "Digital Lemons" },
      { title: "Green Day Medley" },
      { title: "Bulls On Parade" },
      { title: "Two Weeks Past" },
      { title: "Mr. Brightside" },
      { title: "Buddy Holly" },
      { title: "So Naive" },
      { title: "Higher" },
      { title: "Sugar We're Going Down" }
    ] // Add setlist once available
  },

  "deer-park-3-7": {
      title: "Live at Deer Park 3/7",
      heroImages: ["/band2.webp"],
      videos: [
        "lKAoMPVZjPA", 
        "njNXVgItRrQ",
        "n7u4uDErGx4",
        "6ibyAyEUBaI",
        "XRWI3JZr-oY",
        "4QrozbzBDZw",
        "Pk15vTlhkPs",
        "Mdfz0747jPQ",
        "47At1VIU0aQ",
        "HNluM8BVYMY",
        "Ap0LqNnPl2M",
        "zFt7T11sSb0",
        "3jb0-me2Ukc",
        "XqYa3la-Mv4",
        "erNMYMCVqwo",
        "jt5VT5a-Cqw",
        "H0Xzyqsf83I",
        "f8tvhMr0QcA",
        "QZIxEy1jUHY",
        "ry6CEWvaOR0",
        "vXufkCqhFbM",
        "tzu_C7VeHHA",
        "jeeloZJ6bCs",
        "1ZKG-lNnwF0",
        "DWYGrfQdEyY",
        "evwPV-l6SaQ",
        "OFNiFW6X5bs",
        "cAoCIGsDLOY",
        "lU-Ttx8YxcU",
        "KTRabY1d8Rc",
        "cmPlzl-RmFw",
        "TeH0aucLAJc",
        "31vzVVi7YRY",
        "rR2_uP29220",
        "_6cj5js-5xA",
        "TsNN5lmJF20",
        "kDnWD7Y2fwE",
        "_7epDe7eZqg"
      ],
      setlist: [{ title: "Are You Gonna Be My Girl" },
        { title: "Santeria" },
        { title: "Flagpole Sitta" },
        { title: "Cocaine" },
        { title: "Your Love" },
        { title: "Sunday Morning" },
        { title: "Kiwi" },
        { title: "For Whom The Bell Tolls" },
        { title: "Good Times Bad Times" },
        { title: "Zombie" },
        { title: "FRM" },
        { title: "Last Nite" },
        { title: "All The Small Things" },
        { title: "Kilby Girl" },
        { title: "Circling Vultures->Creep" },
        { title: "Enter Sandman" },
        { title: "Everybody Talks" },
        { title: "Plush" },
        { title: "Beautiful Disaster" },
        { title: "War Pigs" },
        { title: "One Last Breath" },
        { title: "Teenage Dirtbag" },
        { title: "Air Raid" },
        { title: "Simple Man" },
        { title: "Chop Suey" },
        { title: "Fat Lip" },
        { title: "Higher" },
        { title: "Inferno" },
        { title: "The Middle" },
        { title: "Flies of Desire" },
        { title: "Digital Lemons -> Killing in the Name" },
        { title: "Basket Case -> Longview" },
        { title: "Naive" },
        { title: "Man in the Box" },
        { title: "Two Weeks Past" },
        { title: "Walk" },
        { title: "Mr. Brightside" }
      ]
    },

    "conch-6-20": {
      title: "Conch Island",
      pagetitle: "Live At Conch 6/20",
      date: "June 20, 2025",
      location: "Rehobeth Beach, DE",
      poster: "/showposters/conch620.webp",
      heroImages: ["/CONCH620PHOTOS/Image93.webp"],
      flyerImage: "showposters/conch620.webp",
      photos: Array.from({ length: 506 }, (_, i) =>
        `/CONCH620PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "NeiwHmvvFtQ", "SN-QV6f-sE0"
      ],
      setlist: [{ title: "Are You Gonna Be My Girl" },
        { title: "Good Times Bad Times" },
        { title: "Interstate Love Song" },
        { title: "Simple Man -> Cocaine" },
        { title: "The Rock Show" },
        { title: "The Anthem" },
        { title: "Master of Puppets -> Enter Sandman" },
        { title: "Plush" },
        { title: "Everybody Talks" },
        { title: "Kilby Girl" },
        { title: "Teenage Dirtbag" },
        { title: "Sunday Morning" },
        { title: "Gives You Hell" },
        { title: "FRM" },
        { title: "Semi-Charmed Life" },
        { title: "My Own Worst Enemy" },
        { title: "Zombie" },
        { title: "All The Small Things" },
        { title: "Chop Suey" },
        { title: "Freebird" },
        { title: "One Last Breath" },
        { title: "My Own Infenro" },
        { title: "Even Flow" },
        { title: "Sugar We're Going Down" },
        { title: "The Middle" },
        { title: "Flies of Desire" },
        { title: "Higher" },
        { title: "Everlong" },
        { title: "Killing in the Name" },
        { title: "111" },
        { title: "Ace of Spades" },
        { title: "Man in the Box" },
        { title: "Two Weeks Past" },
        { title: "Mr. Brightside" },
      ] // Add setlist once available
    },
    
    "smyrna": {
      title: "Smyrna At Nite",
      pagetitle: "Live At Smyrna @ Nite Festival 6/14",
      date: "June 14, 2025",
      location: "Smyrna, DE",
      poster: "/showposters/smyrna.webp",
      heroImages: ["/SMYRNAPHOTOS/Image93.webp"],
      flyerImage: "showposters/smyrna.webp",
      photos: Array.from({ length: 747 }, (_, i) =>
        `/SMYRNAPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "uvWebE-O3Yc"
      ],
      setlist: [{ title: "All The Small Things" },
        { title: "Cocaine" },
        { title: "FRM" },
        { title: "Nothing Left" },
        { title: "So Naive" },
        { title: "Two Weeks Past" },
        { title: "My Own Inferno" },
        { title: "Digital Lemons" },
        { title: "The Middle" },
        { title: "Flies Of Desire" }
      ] // Add setlist once available
    },

    "punkflea": {
      title: "Punk Rock Flea Market",
      pagetitle: "Live At Aetna Fire Hall 5/4",
      date: "May 4, 2025",
      location: "Newark, DE",
      poster: "/showposters/punkflea.webp",
      heroImages: ["/PUNKPHOTOS/Image01.webp"],
      flyerImage: "showposters/punkflea.webp",
      photos: Array.from({ length: 2 }, (_, i) =>
        `/PUNKPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "QA5EwDvtgok"
      ],
      setlist: [{ title: "Nothing Left" },
        { title: "FRM" },
        { title: "So Naive" },
        { title: "Two Weeks Past" },
        { title: "My Own Inferno" },
        { title: "111" },
        { title: "Dear Maria, Count Me In" }
      ] // Add setlist once available
    },

    
    "cats": {
      title: "Cat's 21st Birthday",
      pagetitle: "Live in Jersey 6/14",
      date: "June 14, 2025",
      location: "Cherry Hill, NJ",
      poster: "/CATPHOTOS/Image01.webp",
      heroImages: ["/CATPHOTOS/Image01.webp"],
      flyerImage: "CATPHOTOS/Image01.webp",
      photos: Array.from({ length: 2 }, (_, i) =>
        `/CATPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "u_bvUjIfDrs"
      ],
      setlist: [{ title: "Even Flow" },
        { title: "One Last Breath" },
        { title: "The Middle" },
        { title: "Everlong" },
        { title: "Higher" },
        { title: "Fat Lip" },
        { title: "Are You Gonna Be My Girl?" },
        { title: "Kilby Girl" },
        { title: "Two Weeks Past" },
        { title: "American Idiot" },
        { title: "Interstate Love Song" },
        { title: "Dumpweed" },
        { title: "The Rock Show" },
        { title: "All The Small Things" },
        { title: "Dammit" },
        { title: "Teenage Dirtbag" },
        { title: "The Anthem" },
        { title: "(Like It's) Cocaine" },
        { title: "Everybody Talks" },
        { title: "Your Love" },
        { title: "Gives You Hell" },
        { title: "Stacy's Mom" },
        { title: "Semi-Charmed Life" },
        { title: "FRM" },
        { title: "Baby" },
        { title: "Buddy Holly" },
        { title: "Mr. Brightside" }
      ] // Add setlist once available
    },

    "dpbotb": {
      title: "Deer Park Battle of the Bands",
      pagetitle: "Live at Deer Park Tavern 5/14",
      date: "May 14, 2025",
      location: "Newark, DE",
      poster: "/showposters/dpbotb.webp",
      heroImages: ["/showposters/dpbotb.webp"],
      flyerImage: "showposters/dpbotb.webp",
      photos: Array.from({ length: 0 }, (_, i) =>
        `/DPBOTBPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "mPbwkcQpg30"
      ],
      setlist: [
        { title: "Are You Gonna Be My Girl (soundcheck)" },
        { title: "Zombie" },
        { title: "Last Nite" },
        { title: "Semi-Charmed Life" },
        { title: "(Like It's) Cocaine" },
        { title: "All The Small Things" },
        { title: "Sex on Fire" },
        { title: "Sweet Home Alabama" },
        { title: "Kilby Girl" },
        { title: "FRM" },
        { title: "Everybody Talks" },
        { title: "Your Love" },
        { title: "Two Weeks Past" },
        { title: "Flagpole Sitta" },
        { title: "Circling Vultures -> Creep" },
        { title: "Bulls On Parade" },
        { title: "The Middle" },
        { title: "Everlong" },
        { title: "111" },
        { title: "Killing in the Name" },
        { title: "Sugar We're Goin Down" },
        { title: "Digital Lemons" },
        { title: "Chop Suey" }
      ] // Add setlist once available
    },

    
    "trapt": {
      title: "Hafltime Music w/ Trapt",
      pagetitle: "Live at Halftime Music 5/16 (accompanied by Jake (Arkum) and Lex (Crashout)",
      date: "May 16, 2025",
      location: "Newark, DE",
      poster: "/showposters/trapt.webp",
      heroImages: ["/showposters/trapt.webp"],
      flyerImage: "showposters/trapt.webp",
      photos: Array.from({ length: 0 }, (_, i) =>
        `/TRAPTPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "YM1XBMqttS8"
      ],
      setlist: [{ title: "(Like It's) Cocaine" },
        { title: "All The Small Things" },
        { title: "Nothing Left" },
        { title: "FRM" },
        { title: "My Own Worst Enemy" },
        { title: "My Own Inferno" },
        { title: "Digital Lemons" },
        { title: "Killing in the Name (jam)" },
        { title: "111" },
        { title: "Two Weeks Past" },
        { title: "So Naive" }
      ] // Add setlist once available
    },
    "botb3": {
      title: "VG at WVUD BOTB 2025",
      pagetitle: "Live at UD's Trabant Student Center",
      date: "March 8, 2025",
      location: "Newark, DE",
      poster: "/showposters/botb3.webp",
      heroImages: ["/BOTB3PHOTOS/Image02.webp"],
      flyerImage: "showposters/botb3.webp",
      photos: Array.from({ length: 7 }, (_, i) =>
        `/BOTB3PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "4JR0LsW9OVQ"
      ],
      setlist: [{ title: "Kilby Girl" },
        { title: "Digital Lemons" },
        { title: "Flies of Desire" },
        { title: "Two Weeks Past" }
       
      ] // Add setlist once available
    },
    "swim": {
      title: "VG At UD Swim House",
      pagetitle: "Live on Prospect",
      date: "May 10, 2025",
      location: "Newark, DE",
      poster: "/showposters/swim2.webp",
      heroImages: ["/SWIMPHOTOS/Image13.webp"],
      flyerImage: "showposters/swim2.webp",
      photos: Array.from({ length: 17 }, (_, i) =>
        `/SWIMPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "FDXyNAUVeiA"
      ],
      setlist: [{ title: "American Idiot" },
        { title: "All The Small Things" },
        { title: "Gives You Hell" },
        { title: "My Own Worst Enemy" },
        { title: "Stacy's Mom" },
        { title: "(Like It's) Cocaine" },
        { title: "Hot For Teacher" },
        { title: "Santeria" },
        { title: "Sunday Morning" },
        { title: "Your Love" },
        { title: "Semi-Charmed Life" },
        { title: "Teenage Dirtbag" },
        { title: "Simple Man" },
        { title: "Zombie" },
        { title: "FRM" },
        { title: "Sweet Home Alabama" },
        { title: "Jessie's Girl" },
        { title: "Kiwi" },
        { title: "Big Me" },
        { title: "War Pigs" },
        { title: "Breaking The Law" },
        { title: "Circling Vultures -> Creep" },
        { title: "Enter Sandman" },
        { title: "Higher" },
        { title: "One Last Breath" },
        { title: "I Write Sins Not Tragedies" },
        { title: "Killing In The Name" },
      ] // Add setlist once available
    },
    "union": {
      title: "VG At Union Firehouse",
      pagetitle: "Live at Union Firehouse 5/10",
      date: "May 10, 2025",
      location: "Mount Holly, NJ",
      poster: "/showposters/union2.webp",
      heroImages: ["/UNIONPHOTOS/Image93.webp"],
      flyerImage: "showposters/union2.webp",
      photos: Array.from({ length: 165 }, (_, i) =>
        `/UNIONPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "RB4-hLiiffo"
      ],
      setlist: [{ title: "(Like It's) Cocaine" },
        { title: "111" },
        { title: "Digital Lemons" },
        { title: "Flies of Desire" },
        { title: "Fat Lip" },
        { title: "(Like It's) Cocaine" },
        { title: "Two Weeks Past" },
        { title: "The Anthem" },
       
      ] // Add setlist once available
    },

    "udress": {
      title: "VG At UDress",
      pagetitle: "Live at Trabant 5/3",
      date: "May 3, 2025",
      location: "Newark, DE",
      poster: "/showposters/UDRESS.webp",
      heroImages: ["/showposters/UDRESS.webp"],
      flyerImage: "showposters/UDRESS.webp",
      photos: Array.from({ length: 0 }, (_, i) =>
        `/UDRESSPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "W6bsTxICw1I"
      ],
      setlist: [{ title: "Jessie's Girl" },
        { title: "111" },
        { title: "Everlong" },
       
      ] // Add setlist once available
    },

    "dp-5-2": {
      title: "VG At Deer Park Tavern",
      pagetitle: "Live in Newark 5/2",
      date: "May 2, 2025",
      location: "Newark, DE",
      poster: "/showposters/DP52.webp",
      heroImages: ["/DP52PHOTOS/Image11.webp"],
      flyerImage: "showposters/DP52.webp",
      photos: Array.from({ length: 12 }, (_, i) =>
        `/DP52PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "cpibspIbMSA"
      ],
      setlist: [{ title: "Dear Maria, Count Me In" },
        { title: "Even Flow" },
        { title: "Everlong" },
        { title: "Fat Lip" },
        { title: "111" },
        { title: "I Write Sins Not Tragedies" },
        { title: "Sugar We're Goin' Down" },
        { title: "Digital Lemons->Killing in the Name" },
        { title: "One Last Breath" },
        { title: "You Shook Me All Night Long" },
        { title: "Hot For Teacher" },
        { title: "Teenagers" },
        { title: "Cocaine" },
        { title: "Your Love" },
        { title: "The Anthem" },
        { title: "War Pigs" },
        { title: "Sex on Fire" },
        { title: "FRM" },
        { title: "Master of Puppets -> Enter Sandman" },
        { title: "My Own Worst Enemy" },
        { title: "Kiwi" },
        { title: "Kilby Girl" },
        { title: "Nothing Left" },
        { title: "Jessie's Girl" },
        { title: "Gives You Hell" },
        { title: "Cult of Personality" },
        { title: "Circling Vultures" },
        { title: "All the Small Things" },
        { title: "Chop Suey" },
        { title: "Stacy's Mom" },
        { title: "Simple Man" },
        { title: "Semi-Charmed Life" }
       
      ] // Add setlist once available
    },
    
    "UDANCEBOTB": {
      title: "VG At UDance BOTB",
      pagetitle: "Live in Perkins 5/3 (accompanied by Lex from Crashout)",
      date: "May 3, 2025",
      location: "Newark, DE",
      poster: "/showposters/UDANCE.webp",
      heroImages: ["/showposters/UDANCE.webp"],
      flyerImage: "showposters/UDANCE.webp",
      photos: Array.from({ length: 0 }, (_, i) =>
        `/UDANCEPHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
      ),
      videos: [
        "SLtvzkSch7Y", "INykdmb_llQ", "noTDq7pnfUo", "A_11INrEEy8",
        "SP8wjamfwxQ", "6Kl7cCHjuiQ", "mn2hx0V-0Oc", "424uRmJh7rM",
        "Bk5au-c22Ts", "MRvpBt4bo_g", 
        "y66n-K9xwdo"
      ],
      setlist: [{ title: "Stacy's Mom" },
        { title: "Teenage Dirtbag" },
        { title: "All the Small Things" },
        { title: "Zombie" },
        { title: "Sunday Morning" },
        { title: "Two Weeks Past" },
        { title: "Flies of Desire" },
        { title: "Everlong" },
        { title: "Killing in the Name" },
       
      ] // Add setlist once available
    },

    "rooney-7-12": {
    title: "Catherine Rooney's",
    date: "July 12, 2025",
    pagetitle: "Live At Rooneys 7/12 (update in progress)",
    location: "Wilmington, DE",
    poster: "VGPS3.png",
    heroImages: ["/band2.webp"],
    flyerImage: "VGPS3.png",
    photos: Array.from({ length: 878 }, (_, i) =>
      `/DP1129PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "n7u4uDErGx4", "6ibyAyEUBaI", "XRWI3JZr-oY", "4QrozbzBDZw", "Pk15vTlhkPs",
      "Mdfz0747jPQ", "47At1VIU0aQ", "HNluM8BVYMY", "Ap0LqNnPl2M", "zFt7T11sSb0",
      "3jb0-me2Ukc", "XqYa3la-Mv4", "erNMYMCVqwo", "jt5VT5a-Cqw", "H0Xzyqsf83I",
      "f8tvhMr0QcA", "QZIxEy1jUHY", "ry6CEWvaOR0", "vXufkCqhFbM", "tzu_C7VeHHA",
      "jeeloZJ6bCs", "1ZKG-lNnwF0", "DWYGrfQdEyY", "evwPV-l6SaQ", "OFNiFW6X5bs",
      "cAoCIGsDLOY", "lU-Ttx8YxcU", "KTRabY1d8Rc", "cmPlzl-RmFw", "TeH0aucLAJc",
      "31vzVVi7YRY", "rR2_uP29220", "_6cj5js-5xA", "TsNN5lmJF20", "kDnWD7Y2fwE",
      "_7epDe7eZqg"
    ],
    setlist: [
      { title: "All the Small Things", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "The Anthem" },
      { title: "My Own Worst Enemy" },
      { title: "Gives You Hell", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Kilby Girl" },
      { title: "(Like It's) Cocaine", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Stacy's Mom" },
      { title: "She Looks So Perfect" },
      { title: "The Rock Show" },
      { title: "American Idiot", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Creep" },
      { title: "FRM" },
      { title: "Teenagers" },
      { title: "Are You Gonna Be My Girl?" },
      { title: "Phineas and Ferb" },
      { title: "Santeria" },
      { title: "You Shook Me All Night Long" },
      { title: "Zombie" },
      { title: "Sex on Fire" },
      { title: "Everybody Talks" },
      { title: "Dammit" },
      { title: "Semi-Charmed Life" },
      { title: "Teenage Dirtbag" },
      { title: "Simple Man" },
      { title: "Your Love" },
      { title: "Master of Puppets -> Enter Sandman" },
      { title: "Kiwi" },
      { title: "Nothing Left" },
      { title: "Freebird" },
      { title: "Sugar We're Goin' Down" },
      { title: "Flies of Desire" },
      { title: "Higher" },
      { title: "Dear Maria" },
      { title: "111" },
      { title: "I Write Sins" },
      { title: "Digital Lemons -> Killing in the Name" },
      { title: "The Middle" },
      { title: "One Last Breath" },
      { title: "Buddy Holly" },
      { title: "Basket Case -> Longview" },
      { title: "Mississippi Queen" },
      { title: "Two Weeks Past" },
      { title: "Mr. Brightside" },

    ]
  },//update when able

  "station-7-16": {
    title: "Staion 142",
    date: "July 16, 2025",
    pagetitle: "Live At Station 142 7/16 (update in progress)",
    location: "West Chester, PA",
    poster: "VGPS3.png",
    heroImages: ["/band2.webp"],
    flyerImage: "VGPS3.png",
    photos: Array.from({ length: 878 }, (_, i) =>
      `/DP1129PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "n7u4uDErGx4", "6ibyAyEUBaI", "XRWI3JZr-oY", "4QrozbzBDZw", "Pk15vTlhkPs",
      "Mdfz0747jPQ", "47At1VIU0aQ", "HNluM8BVYMY", "Ap0LqNnPl2M", "zFt7T11sSb0",
      "3jb0-me2Ukc", "XqYa3la-Mv4", "erNMYMCVqwo", "jt5VT5a-Cqw", "H0Xzyqsf83I",
      "f8tvhMr0QcA", "QZIxEy1jUHY", "ry6CEWvaOR0", "vXufkCqhFbM", "tzu_C7VeHHA",
      "jeeloZJ6bCs", "1ZKG-lNnwF0", "DWYGrfQdEyY", "evwPV-l6SaQ", "OFNiFW6X5bs",
      "cAoCIGsDLOY", "lU-Ttx8YxcU", "KTRabY1d8Rc", "cmPlzl-RmFw", "TeH0aucLAJc",
      "31vzVVi7YRY", "rR2_uP29220", "_6cj5js-5xA", "TsNN5lmJF20", "kDnWD7Y2fwE",
      "_7epDe7eZqg"
    ],
    setlist: [
      { title: "Are You Gonna Be My Girl", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Kiwi" },
      { title: "The Anthem" },
      { title: "Santeria", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Stacy's Mom" },
      { title: "Cocaine", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Everybody Talks" },
      { title: "Master->Sandman" },
      { title: "Creep" },
      { title: "Dammit", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Nothing Left" },
      { title: "Kilby Girl" },
      { title: "Your Love" },
      { title: "Simple Man" },
      { title: "Zombie" },
      { title: "Phineas and Ferb" },
      { title: "All the Small Things" },
      { title: "FRM" },
      { title: "American Idiot" },
      { title: "She Looks So Perfect" },
      { title: "Gives You Hell" },
      { title: "My Own Worst Enemy" },
      { title: "Teenage Dirtbag" },
      { title: "The Rock Show" },
      { title: "Teenagers" },
      { title: "Semi-Charmed Life" },
      { title: "Sex on Fire" },
      { title: "Freebird" },
      { title: "Flagpole Sitta" },
      { title: "Interstate Love Song" },
      { title: "Chop Suey" },
      { title: "My Own Inferno" },
      { title: "Sugar We're Goin' Down" },
      { title: "Higher" },
      { title: "I Write Sins Not Tragedies" },
      { title: "111" },
      { title: "The Middle" },
      { title: "Digital Lemons" },
      { title: "One Last Breath" },
      { title: "Killing in the Name" },
      { title: "You Shook Me All Night Long" },
      { title: "Buddy Holly" },
      { title: "Basket Case -> Longview" },
      { title: "Two Weeks Past" },
      { title: "Mississippi Queen" },
      { title: "Party in the USA" },
      { title: "So Naive" },
      { title: "Man in the Box" },
      { title: "Bulls on Parade" },
      { title: "War Pigs" },
      { title: "Mr. Brightside" }
    ]
  },//update when able, we added flagpole and interstate I think so check
  "bayard-7-25": {
    title: "Bayard House",
    date: "July 25, 2025",
    pagetitle: "Live At Bayard House 7/25 (update in progress)",
    location: "Wilmington, DE",
    poster: "VGPS3.png",
    heroImages: ["/band2.webp"],
    flyerImage: "VGPS3.png",
    photos: Array.from({ length: 878 }, (_, i) =>
      `/DP1129PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "n7u4uDErGx4", "6ibyAyEUBaI", "XRWI3JZr-oY", "4QrozbzBDZw", "Pk15vTlhkPs",
      "Mdfz0747jPQ", "47At1VIU0aQ", "HNluM8BVYMY", "Ap0LqNnPl2M", "zFt7T11sSb0",
      "3jb0-me2Ukc", "XqYa3la-Mv4", "erNMYMCVqwo", "jt5VT5a-Cqw", "H0Xzyqsf83I",
      "f8tvhMr0QcA", "QZIxEy1jUHY", "ry6CEWvaOR0", "vXufkCqhFbM", "tzu_C7VeHHA",
      "jeeloZJ6bCs", "1ZKG-lNnwF0", "DWYGrfQdEyY", "evwPV-l6SaQ", "OFNiFW6X5bs",
      "cAoCIGsDLOY", "lU-Ttx8YxcU", "KTRabY1d8Rc", "cmPlzl-RmFw", "TeH0aucLAJc",
      "31vzVVi7YRY", "rR2_uP29220", "_6cj5js-5xA", "TsNN5lmJF20", "kDnWD7Y2fwE",
      "_7epDe7eZqg"
    ],
    setlist: [
      { title: "Rock And Roll", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenage Dirtbag" },
      { title: "All The Small Things" },
      { title: "Enter Sandman", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Circling Vultures" },
      { title: "Creep", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenagers" },
      { title: "You Shook Me All Night Long" },
      { title: "Gives You Hell" },
      { title: "(Like It's) Cocaine", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Zombie" },
      { title: "Creeping Death (ft. Tom)" },
      { title: "Cigarette Daydreams" },
      { title: "Air Raid" },
      { title: "Times Like These" },
      { title: "Sunday Morning" },
      { title: "American Idiot" },
      { title: "Nothing Left" },
      { title: "War Pigs" },
      { title: "Cult Of Personality" },
      { title: "Flagpole Sitta" },
      { title: "Beautiful Disaster" },
      { title: "Kilby Girl" },
      { title: "Sweet Home Alabama" },
      { title: "Everybody Talks" },
      { title: "FRM" },
      { title: "Sex On Fire" },
      { title: "Chop Suey" },
      { title: "My Own Inferno" },
      { title: "The Middle" },
      { title: "Digital Lemons" },
      { title: "Killing In The Name" },
      { title: "One Last Breath" },
      { title: "Higher" },
      { title: "Everlong" },
      { title: "Two Weeks Past" },
      { title: "Walk" },
      { title: "Basket Case" },
      { title: "Encore: Bulls On Parade" }
    ]
  },//update when able
"conch-8-8": {
    title: "Conch Island",
    date: "August 8, 2025",
    pagetitle: "Live At Conch Island 8/8 (update in progress)",
    location: "Rehobeth Beach, DE",
    poster: "VGPS3.png",
    heroImages: ["/band2.webp"],
    flyerImage: "VGPS3.png",
    photos: Array.from({ length: 878 }, (_, i) =>
      `/DP1129PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "n7u4uDErGx4", "6ibyAyEUBaI", "XRWI3JZr-oY", "4QrozbzBDZw", "Pk15vTlhkPs",
      "Mdfz0747jPQ", "47At1VIU0aQ", "HNluM8BVYMY", "Ap0LqNnPl2M", "zFt7T11sSb0",
      "3jb0-me2Ukc", "XqYa3la-Mv4", "erNMYMCVqwo", "jt5VT5a-Cqw", "H0Xzyqsf83I",
      "f8tvhMr0QcA", "QZIxEy1jUHY", "ry6CEWvaOR0", "vXufkCqhFbM", "tzu_C7VeHHA",
      "jeeloZJ6bCs", "1ZKG-lNnwF0", "DWYGrfQdEyY", "evwPV-l6SaQ", "OFNiFW6X5bs",
      "cAoCIGsDLOY", "lU-Ttx8YxcU", "KTRabY1d8Rc", "cmPlzl-RmFw", "TeH0aucLAJc",
      "31vzVVi7YRY", "rR2_uP29220", "_6cj5js-5xA", "TsNN5lmJF20", "kDnWD7Y2fwE",
      "_7epDe7eZqg"
    ],
    setlist: [
      { title: "Rock And Roll", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenage Dirtbag" },
      { title: "All The Small Things" },
      { title: "Enter Sandman", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Circling Vultures" },
      { title: "Creep", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenagers" },
      { title: "You Shook Me All Night Long" },
      { title: "Gives You Hell" },
      { title: "(Like It's) Cocaine", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Zombie" },
      { title: "Creeping Death (ft. Tom)" },
      { title: "Cigarette Daydreams" },
      { title: "Air Raid" },
      { title: "Times Like These" },
      { title: "Sunday Morning" },
      { title: "American Idiot" },
      { title: "Nothing Left" },
      { title: "War Pigs" },
      { title: "Cult Of Personality" },
      { title: "Flagpole Sitta" },
      { title: "Beautiful Disaster" },
      { title: "Kilby Girl" },
      { title: "Sweet Home Alabama" },
      { title: "Everybody Talks" },
      { title: "FRM" },
      { title: "Sex On Fire" },
      { title: "Chop Suey" },
      { title: "My Own Inferno" },
      { title: "The Middle" },
      { title: "Digital Lemons" },
      { title: "Killing In The Name" },
      { title: "One Last Breath" },
      { title: "Higher" },
      { title: "Everlong" },
      { title: "Two Weeks Past" },
      { title: "Walk" },
      { title: "Basket Case" },
      { title: "Encore: Bulls On Parade" }
    ]
  },//update when able
    "splitz": {
    title: "Splitz",
    date: "August 22, 2025",
    pagetitle: "Live At Splitz 8/22 (update in progress)",
    location: "Maple Shade, NJ",
    poster: "VGPS3.png",
    heroImages: ["/band2.webp"],
    flyerImage: "VGPS3.png",
    photos: Array.from({ length: 878 }, (_, i) =>
      `/DP1129PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "n7u4uDErGx4", "6ibyAyEUBaI", "XRWI3JZr-oY", "4QrozbzBDZw", "Pk15vTlhkPs",
      "Mdfz0747jPQ", "47At1VIU0aQ", "HNluM8BVYMY", "Ap0LqNnPl2M", "zFt7T11sSb0",
      "3jb0-me2Ukc", "XqYa3la-Mv4", "erNMYMCVqwo", "jt5VT5a-Cqw", "H0Xzyqsf83I",
      "f8tvhMr0QcA", "QZIxEy1jUHY", "ry6CEWvaOR0", "vXufkCqhFbM", "tzu_C7VeHHA",
      "jeeloZJ6bCs", "1ZKG-lNnwF0", "DWYGrfQdEyY", "evwPV-l6SaQ", "OFNiFW6X5bs",
      "cAoCIGsDLOY", "lU-Ttx8YxcU", "KTRabY1d8Rc", "cmPlzl-RmFw", "TeH0aucLAJc",
      "31vzVVi7YRY", "rR2_uP29220", "_6cj5js-5xA", "TsNN5lmJF20", "kDnWD7Y2fwE",
      "_7epDe7eZqg"
    ],
    setlist: [
      { title: "Rock And Roll", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenage Dirtbag" },
      { title: "All The Small Things" },
      { title: "Enter Sandman", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Circling Vultures" },
      { title: "Creep", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Teenagers" },
      { title: "You Shook Me All Night Long" },
      { title: "Gives You Hell" },
      { title: "(Like It's) Cocaine", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Zombie" },
      { title: "Creeping Death (ft. Tom)" },
      { title: "Cigarette Daydreams" },
      { title: "Air Raid" },
      { title: "Times Like These" },
      { title: "Sunday Morning" },
      { title: "American Idiot" },
      { title: "Nothing Left" },
      { title: "War Pigs" },
      { title: "Cult Of Personality" },
      { title: "Flagpole Sitta" },
      { title: "Beautiful Disaster" },
      { title: "Kilby Girl" },
      { title: "Sweet Home Alabama" },
      { title: "Everybody Talks" },
      { title: "FRM" },
      { title: "Sex On Fire" },
      { title: "Chop Suey" },
      { title: "My Own Inferno" },
      { title: "The Middle" },
      { title: "Digital Lemons" },
      { title: "Killing In The Name" },
      { title: "One Last Breath" },
      { title: "Higher" },
      { title: "Everlong" },
      { title: "Two Weeks Past" },
      { title: "Walk" },
      { title: "Basket Case" },
      { title: "Encore: Bulls On Parade" }
    ]
  },//update when able
  "rons-8-23": {
    title: "Captain Ron's",
    date: "August 23, 2025",
    pagetitle: "Live At Captain Ron's 8/23 (update in progress)",
    location: "Wilmington, DE",
    poster: "VGPS3.png",
    heroImages: ["/band2.webp"],
    flyerImage: "VGPS3.png",
    photos: Array.from({ length: 878 }, (_, i) =>
      `/DP1129PHOTOS/Image${String(i + 1).padStart(2, '0')}.webp`
    ),
    videos: [
      "n7u4uDErGx4", "6ibyAyEUBaI", "XRWI3JZr-oY", "4QrozbzBDZw", "Pk15vTlhkPs",
      "Mdfz0747jPQ", "47At1VIU0aQ", "HNluM8BVYMY", "Ap0LqNnPl2M", "zFt7T11sSb0",
      "3jb0-me2Ukc", "XqYa3la-Mv4", "erNMYMCVqwo", "jt5VT5a-Cqw", "H0Xzyqsf83I",
      "f8tvhMr0QcA", "QZIxEy1jUHY", "ry6CEWvaOR0", "vXufkCqhFbM", "tzu_C7VeHHA",
      "jeeloZJ6bCs", "1ZKG-lNnwF0", "DWYGrfQdEyY", "evwPV-l6SaQ", "OFNiFW6X5bs",
      "cAoCIGsDLOY", "lU-Ttx8YxcU", "KTRabY1d8Rc", "cmPlzl-RmFw", "TeH0aucLAJc",
      "31vzVVi7YRY", "rR2_uP29220", "_6cj5js-5xA", "TsNN5lmJF20", "kDnWD7Y2fwE",
      "_7epDe7eZqg"
    ],
    setlist: [
      { title: "Teenagers", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Dumpweed" },
      { title: "1985" },
      { title: "Gives You Hell", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "The Anthem" },
      { title: "Are You Gonna Be My Girl", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Semi-Charmed Life" },
      { title: "Teenage Dirtbag" },
      { title: "Sk8er Boi" },
      { title: "Master of Puppets -> Enter Sandman", link: "https://www.youtube.com/watch?v=QVKVcALMHoY" },
      { title: "Plush" },
      { title: "All the Small Things" },
      { title: "Nothing Left" },
      { title: "Simple Man" },
      { title: "My Own Worst Enemy" },
      { title: "The Rock Show" },
      { title: "FRM" },
      { title: "Creep" },
      { title: "Santeria" },
      { title: "Sunday Morning" },
      { title: "Everybody Talks" },
      { title: "Breaking the Law" },
      { title: "(Like It's) Cocaine" },
      { title: "Good Times Bad Times -> Stairway to Heaven" },
      { title: "Paranoid" },
      { title: "Flagpole Sitta" },
      { title: "Circling Vultures" },
      { title: "Zombie" },
      { title: "One Last Breath" },
      { title: "Even Flow" },
      { title: "Higher" },
      { title: "111" },
      { title: "The Middle" },
      { title: "Sugar We're Goin' Down" },
      { title: "Everlong" },
      { title: "Two Weeks Past" },
      { title: "Welcome To Paradise" },
      { title: "Bulls On Parade" },
      { title: "So Naive" },
      { title: "Mr. Brightside" },
      { title: "Digital Lemons" },
      { title: "Killing In The Name" }

    ]
  },//update when able, fix order
};
